# Generated by Django 3.0.4 on 2020-03-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_id', models.TextField(blank=True, null=True)),
                ('investor_id', models.IntegerField(blank=True, null=True)),
                ('bond_symbol', models.TextField(blank=True, null=True)),
                ('no_shares', models.IntegerField(blank=True, null=True)),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('purchase_date', models.TextField(blank=True, null=True)),
                ('coupon', models.FloatField(blank=True, null=True)),
                ('yield_field', models.FloatField(blank=True, db_column='yield', null=True)),
            ],
            options={
                'db_table': 'Bond',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_id', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Investor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.TextField(blank=True, null=True)),
                ('investor_id', models.IntegerField(blank=True, null=True)),
                ('stock_symbol', models.TextField(blank=True, null=True)),
                ('no_shares', models.IntegerField(blank=True, null=True)),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('purchase_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Stock',
                'managed': False,
            },
        ),
    ]
